default_platform(:ios)

platform :ios do

  desc "Build and test"
  lane :build do
    xcbuild
    scan
  end

  desc "Archive"
  lane :archive do
    xcarchive(destination:"generic/platform=iOS", scheme:"BitriseTest", archive_path: "${BITRISE_DEPLOY_DIR}/BitriseTest.xcarchive")
  end

  desc "Archive"
  lane :release do
    gym(destination:"generic/platform=iOS", scheme:"BitriseTest", export_method: "development", build_path: ENV["BITRISE_DEPLOY_DIR"], output_directory: ENV["BITRISE_DEPLOY_DIR"])
  end

end
